import ThemeRegistry from '@/features/theme-registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className='bg-black h-screen w-screen'>
			<ThemeRegistry options={{ key: 'joy' }}>
				<body className={inter.className}>{children}</body>
			</ThemeRegistry>
		</html>
	)
}
